language: java
jdk: oraclejdk8
cache: bundler

sudo: required

before_install:
  - if [ "${TRAVIS_TAG?}" ]; then
      AWS_BUCKET="schema.datacite.org";
      RACK_ENV="production";
      cp .env.production .env;
    else
      AWS_BUCKET="schema.stage.datacite.org";
      RACK_ENV="stage";
      cp .env.stage .env;
    fi
  - rvm install 2.3.1

  - wget https://github.com/jgm/pandoc/releases/download/1.15.2/pandoc-1.15.2-1-amd64.deb
  - sudo dpkg -i pandoc-1.15.2-1-amd64.deb
  - rm pandoc-1.15.2-1-amd64.deb

install:
  - bundle install
  - sudo pip install awscli

script:
  - bundle exec rspec
  # - mvn clean test -B -Droot.dir=build/ -Dindex.html=index.html
  - bundle exec middleman build -e $RACK_ENV --verbose

deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  bucket: $AWS_BUCKET
  local-dir: build
  acl: public_read
  skip_cleanup: true
  region: eu-west-1
  detect_encoding: true
  on:
    all_branches: true

after_deploy:
  - export AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY
  - export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_KEY
  # Allow `awscli` to make requests to CloudFront.
  - aws configure set preview.cloudfront true
  # Invalidate every object in the targeted distribution.
  - if [ "${TRAVIS_TAG?}" ]; then
      - aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_DISTRIBUTION_ID --paths "/*"
    else
      - aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_DISTRIBUTION_ID_STAGE --paths "/*"
      - aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_DISTRIBUTION_ID_TEST --paths "/*"
    fi

notifications:
  slack: datacite:Wt8En0ALoTA6Kjc5EOKNDWxN
  email: false
