language: java
jdk: oraclejdk8
cache: bundler
cache:
  directories:
    - $HOME/.m2

before_install:
  - set -e
  - if [ "${TRAVIS_TAG?}" ]; then
      AWS_BUCKET="schema.datacite.org";
    elif [ "$TRAVIS_BRANCH" == "labs" ]; then
      AWS_BUCKET="schema.labs.datacite.org";
    else
      exit 1;
    fi
  - rvm install 2.2.0

install:
  - bundle install

script:
  - bundle exec middleman build
  - bundle exec rspec
  - mvn -Dtest=ValidationTest,BasicTest test -B

deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  bucket: $AWS_BUCKET
  local-dir: build
  acl: public_read
  skip_cleanup: true
  region: eu-west-1
  detect_encoding: true
  on:
    all_branches: true

notifications:
  slack: datacite:Wt8En0ALoTA6Kjc5EOKNDWxN
